Webcam.attach('#my_camera');


var webcamData = new Array(2);
var intervalManager;
var triggerCounter = 0;
var triggerThreshold = 3;

document.getElementById("triggerThreshold").innerHTML = "Current Threshold: " + triggerThreshold + "%";

function startInterval() {
    intervalManager = setInterval(take_snapshot, 3000);
}

function stopInterval() {
    clearInterval(intervalManager);
}


function take_snapshot() {

    Webcam.snap( function(data_uri) {
        if (document.getElementById('imgResult') == null) {
            webcamData[1] = data_uri;
            document.getElementById('my_result').innerHTML = '<img id = "imgResult" src="' + data_uri + '"/>';
        }
        else
        {
            webcamData[0] = webcamData[1];
            webcamData[1] = data_uri;
            document.getElementById('my_result').innerHTML = '<img id = "imgResult" src="' + webcamData[0] + '"/>';
            document.getElementById('my_result2').innerHTML = '<img id = "imgResult2" src="' + webcamData[1] + '"/>';
            getdiff()
        }
    } );
}

function take_snapshot() {

    Webcam.snap(function(data_uri) {
        if (document.getElementById('imgResult') == null) {
            webcamData[0] = data_uri;
            document.getElementById('my_result').innerHTML = '<img id = "imgResult" src="' + data_uri + '"/>';
        }
        else
        {
            webcamData[1] = webcamData[0];
            webcamData[0] = data_uri;
            document.getElementById('my_result').innerHTML = '<img id = "imgResult" src="' + webcamData[1] + '"/>';
            document.getElementById('my_result2').innerHTML = '<img id = "imgResult2" src="' + webcamData[0] + '"/>';
            getdiff()
        }
    } );
}

function getdiff()
{

    //NOTE: for the following, ARRAY[0] refers to reference image, ARRAY[1] refers to new Image

    var canvas = new Array(2); //represents canvases generated by images
    var images = new Array(2); //represents images
    var ctx = new Array(2); //represents canvas contexts
    var imageData = new Array(2); //represents imageData objects
    var data = new Array(2); //represents imageData subobject needed for our calculations
    canvas[0] = document.getElementById("canvas");
    canvas[1] = document.getElementById("canvas2");
    images[0] = document.getElementById("imgResult");
    images[1] = document.getElementById("imgResult2");
    ctx[0] = canvas[0].getContext('2d');
    ctx[1] = canvas[1].getContext('2d');


    canvas[0].width = images[0].width;
    canvas[0].height = images[0].height;
    ctx[0].drawImage(images[0], 0, 0);
    imageData[0] = ctx[0].getImageData(0,0,images[0].width, images[0].height);
    data[0] = imageData[0].data;

    canvas[1].width = images[1].width;
    canvas[1].height = images[1].height;
    ctx[1].drawImage(images[1], 0, 0);
    imageData[1] = ctx[1].getImageData(0,0,images[1].width, images[1].height);
    data[1] = imageData[1].data;

    var potentialTotal = data[0].length * 255; //maximum potential difference between image 1 and 2;
    var differenceTotal = 0; //total pixel difference between images 1 and 2

    for(var i = 0; i < data[0].length-5; i += 4)
    {
        //This loop handles different RBG values, something that is irrelevant now but might be later.
        differenceTotal += Math.abs((data[1][i] + data[1][i+1] + data[1][i+2]) - (data[0][i] + data[0][i+1] + data[0][i+2]));
    }

    var differenceRatio = (differenceTotal/potentialTotal).toFixed(3) * 100; //ratio measuring actual difference and potential difference
    console.log("Difference Total: " + differenceTotal);
    console.log("Potential Difference: " + potentialTotal);
    console.log("Difference Ratio: " + differenceRatio * 100 + "%");

    document.getElementById("totalDifference").innerHTML = "Total Difference: " + differenceTotal;
    document.getElementById("potentialDifference").innerHTML = "Potential Difference: " + potentialTotal;
    document.getElementById("differenceRatio").innerHTML = "Difference Ratio " + differenceRatio + "%";
    
    if (differenceRatio > triggerThreshold)
    {
        triggerCounter += 1;
        document.getElementById("triggerCounter").innerHTML = "Total Differences over threshold: " + triggerCounter;
    }
}

